# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     James Krieger (jamesmkrieger@gmail.com)
# *
# * Centro Nacional de Biotecnologia, CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


"""
This module will provide ProDy mode import tools.
"""
import numpy as np
import os
import prody

from prody2.objects import (ProDyNpzEnsemble, TrajFrame)
from prody2.constants import ENSEMBLE_WEIGHTS, ZERO
from prody2 import Plugin

from pwem.objects import (String, AtomStruct, SetOfAtomStructs, EMFile,
                          SetOfNormalModes, SetOfPrincipalComponents)
from pwem.protocols import ProtImportFiles

import pyworkflow.object as pwobj
import pyworkflow.protocol.params as params
from pyworkflow.utils import logger, glob


NMD = 0
MODES_NPZ = 1
SCIPION = 2
GROMACS = 3

PDB_FILENAME = 'atoms.pdb'
PSF_FILENAME = 'atoms.psf'
DCD_FILENAME = 'ensemble.dcd'

filesPatternHelp = """Pattern of the files to be imported.\n\n
The pattern can contain standard wildcards such as\n
*, ?, etc, or special ones like ### to mark some\n
digits in the filename as ID.\n\n
NOTE: wildcards and special characters 
('*', '?', '#', ':', '%') cannot appear in the actual path.\n\n
For gromacs modes, the first is for values and this is for vectors"""

class ProDyImportModes(ProtImportFiles):
    """
    Imports ProDy normal modes and molecular ensembles from different
    supported file formats into Scipion-compatible objects.

    AI Generated:

    ProDy Import Modes + Import Ensemble — User Manual
        Overview

        These two protocols are designed to import structural dynamics
        information generated outside Scipion into internal data objects
        that can be used in downstream ProDy- and Scipion-based analyses.

        The first protocol, ProDyImportModes, imports normal mode analysis
        results such as essential motions, principal components, elastic
        network modes, or logistic regression modes.

        The second protocol, ProDyImportEnsemble, imports structural
        ensembles representing multiple conformations of the same system,
        optionally aligning, trimming, filtering, and exporting them into
        formats compatible with later workflows.

        Together, these protocols provide the bridge between external
        dynamics calculations and internal structural interpretation.

        ============================================================
        ProDyImportModes
        ============================================================

        Purpose

        ProDyImportModes imports normal modes from several commonly used
        ProDy-compatible formats and converts them into Scipion normal
        mode objects.

        This protocol is useful when the user has already performed
        dynamics calculations externally and wants to continue analysis
        inside Scipion.

        Supported Input Types

        The protocol supports several mode sources:

        1. ProDy NMD
           Native ProDy normal mode files.

        2. ProDy NPZ
           Serialized ProDy mode objects.

        3. Scipion mode directory
           A previously exported Scipion normal-mode dataset.

        4. Gromacs modes
           Eigenvectors and eigenvalues generated by Gromacs.

        Biological Interpretation

        These modes describe collective structural motions.

        Depending on the imported file, the protocol can recover:

        - Principal component motions from PCA
        - Elastic network modes from GNM/NMA
        - Logistic regression modes
        - Modes derived from molecular dynamics simulations

        Such motions are commonly used to study:

        - domain rearrangements
        - conformational transitions
        - large-scale collective flexibility
        - biologically relevant structural heterogeneity

        Workflow

        The import step identifies the input format and parses the
        corresponding mode file.

        For native NMD files, the protocol automatically infers the
        ProDy mode type from the filename:

        - "pca"    → PCA
        - "logreg" → Logistic Regression Analysis
        - "gnm"    → Gaussian Network Model
        - otherwise → generic NMA

        If no reference structure is provided for NMD import, the
        protocol extracts atomic coordinates from the NMD file and
        creates a temporary structure automatically.

        For NPZ, Scipion, or Gromacs imports, a reference structure
        must normally be supplied so the imported modes can be linked
        to a concrete atomic model.

        Output Generation

        After import, the protocol exports the modes into Scipion format
        and generates a corresponding NMD representation.

        Depending on the imported data, the output object is classified
        automatically as one of the following:

        - SetOfGnmModes
        - SetOfNormalModes
        - SetOfLogisticModes
        - SetOfPrincipalComponents

        This automatic classification depends on:

        - the ProDy object type
        - the number of atoms
        - the eigenvalue distribution

        Practical Notes

        For biological interpretation, it is important that the input
        structure matches the atomic ordering used during the original
        mode calculation.

        Mismatches in atom identity or ordering may lead to incorrect
        interpretation of collective motions.

        ============================================================
        ProDyImportEnsemble
        ============================================================

        Purpose

        ProDyImportEnsemble imports structural ensembles consisting of
        multiple conformations of the same system.

        These ensembles may come from:

        - experimentally derived alternative conformations
        - molecular dynamics trajectories
        - previously generated ProDy ensembles
        - sets of aligned atomic models

        The protocol converts them into a Scipion-compatible
        ProDy ensemble object and optionally produces trajectory and
        per-frame structure outputs.

        Supported Input Types

        The protocol supports two import sources.

        1. Import from files

           Supported ensemble formats include:

           - PDB
           - DCD
           - ens.npz

        2. Import from existing Scipion objects

           Accepted pointers include:

           - AtomStruct
           - SetOfAtomStructs
           - ProDyNpzEnsemble
           - DCD molecular systems

        General Workflow

        The protocol first loads the ensemble according to the selected
        source.

        During import, it attempts to recover:

        - atomic coordinates
        - ensemble labels
        - conformational weights

        If no valid weights are found, equal weights are assigned to
        all conformations.

        Atom Selection and Trimming

        A selection string can be provided to keep only a subset of atoms.

        Common examples include:

        - "all"
        - "protein"
        - "name CA"

        After selection, the protocol tries several strategies to make
        the selected reference structure compatible with the ensemble.

        This is necessary because imported structures may not always
        contain exactly the same atom ordering or atom count.

        If compatibility cannot be established, the protocol raises an
        explicit error.

        From a biological perspective, atom selection is highly useful
        when focusing on:

        - protein backbone motions
        - domain movements
        - reduced coarse-grained representations

        Superposition

        The protocol can optionally superpose the ensemble.

        Available choices are:

        - No superposition
        - Single superposition
        - Iterative superposition

        This step removes rigid-body differences between conformations.

        Biologically, superposition is often essential before comparing
        internal flexibility or extracting meaningful collective motions.

        Saving Additional Outputs

        The protocol can optionally save:

        - aligned PDB files for every conformation
        - DCD trajectory files
        - PSF topology files

        These outputs are useful when interoperating with:

        - ContinuousFlex
        - molecular visualization tools
        - trajectory-based downstream analyses

        Output Objects

        The main output is always a ProDyNpzEnsemble object.

        Depending on the selected options, additional outputs may include:

        - outputTrajectory
        - outputStructures

        Each frame in the resulting ensemble stores:

        - its label
        - its conformational weight

        Practical Recommendations

        When importing DCD trajectories, always provide a matching
        reference structure whenever possible.

        When selecting only part of the structure, verify that the atom
        selection remains biologically meaningful and consistent across
        all conformations.

        If the ensemble contains large rigid-body shifts, enabling
        superposition is strongly recommended before downstream analysis.

        Final Perspective

        These import protocols do not merely convert file formats.

        They standardize external structural dynamics information into
        internally consistent Scipion objects.

        For biological studies, this is critical because downstream
        interpretation of flexibility, collective motions, and
        conformational variability depends strongly on preserving the
        correct correspondence between:

        - atoms
        - coordinates
        - eigenvectors
        - ensemble frames
    """

    _label = 'Import modes'

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        importChoices = self._getImportChoices()
        filesCondition = self._getFilesCondition()

        form.addSection(label='Import modes')

        form.addParam('importFrom', params.EnumParam,
                      choices=importChoices, default=self._getDefaultChoice(),
                      label='Import from',
                      help='Select the type of import.')

        form.addParam('importType', params.EnumParam,
                      choices=['prody nmd', 'prody npz', 'scipion', 'gromacs'],
                      default=NMD,
                      label='Type of modes to import',
                      help='ProDy can support import of modes in various file formats: \n'
                           'native nmd and npz files, a scipion-style directory for a SetOfNormalModes, '
                           'or a gromacs directory with files containing eigenvectors and eigenvalues')

        form.addParam('filesPath', params.PathParam,
                      condition=filesCondition,
                      label="Files directory",
                      help="Directory with the files you want to import.\n\n"
                           "The path can also contain wildcards to select"
                           "from several folders. \n\n"
                           "Examples:\n"
                           "  ~/project/data/day??_files/\n"
                           "Each '?' represents one unknown character\n\n"
                           "  ~/project/data/day*_files/\n"
                           "'*' represents any number of unknown characters\n\n"
                           "  ~/project/data/day##_files/\n"
                           "'##' represents two digits that will be used as "
                           "file ID\n\n"
                           "NOTE: wildcard characters ('*', '?', '#') "
                           "cannot appear in the actual path.)")

        form.addParam('filesPattern', params.StringParam,
                      label='File pattern',
                      condition="importType!=%d" % SCIPION,
                      help=filesPatternHelp)

        form.addParam('filesPattern2', params.StringParam,
                      label='File pattern for eigenvalues',
                      condition="importType==%d" % GROMACS,
                      help=filesPatternHelp)

        form.addParam('inputStructure', params.PointerParam, label="Input structure",
                      pointerClass='AtomStruct', condition="importType!=%d" % NMD,
                      help='The input structure can be an atomic model '
                           '(true PDB) or a pseudoatomic model\n'
                           '(an EM volume converted into pseudoatoms)')

    # --------------------------- STEPS functions ------------------------------
    def _insertAllSteps(self):
        # Insert processing steps
        self._insertFunctionStep('importModesStep')
        self._insertFunctionStep('createOutputStep')

    def importModesStep(self):

        if self.inputStructure.get() is not None:
            pdbFileName = self.inputStructure.get().getFileName()
        else:
            self.inputStructure = AtomStruct(filename=self._getExtraPath("atoms.pdb"))
            pdbFileName = "None"

        args = f'--importType {self.importType} --filesPaths "{self.getMatchFiles()}"' \
            f' --filesPattern2 {self.filesPattern2} --protocolPath {self._getPath()}' \
            f' --pdbFileName {pdbFileName}'

        self.runJob(Plugin.getProgram('import_modes.py', script=True), args)

    def createOutputStep(self):
        fnSqlite = self._getPath('modes.sqlite')

        nmSet = SetOfNormalModes(filename=fnSqlite)
        if len(nmSet) > 1 and not (nmSet[1]._eigenval.get() <= nmSet[2]._eigenval.get()
            or nmSet[1]._eigenval.get() < ZERO):
            nmSet = SetOfPrincipalComponents(filename=fnSqlite)

        if self.importType != NMD:
            nmdFileName = glob(self._getPath('modes.*.nmd'))
        else:
            nmdFileName = self.filesPattern
        nmSet._nmdFileName = String(nmdFileName)

        if self.inputStructure.get() is None:
            outputPdb = AtomStruct(filename=self._getExtraPath("atoms.pdb"))
        else:
            outputPdb = self.inputStructure.get()
        nmSet.setPdb(outputPdb)

        self._defineOutputs(outputStructure=outputPdb)
        self._defineOutputs(outputModes=nmSet)
        self._defineSourceRelation(outputPdb, nmSet)

PDB = 0
DCD = 1
ENS_NPZ = 2

NO_SUP = 0
YES_SUP = 1
ITERPOSE = 2

POINTER_TYPES = 'AtomStruct,SetOfAtomStructs,ProDyNpzEnsemble'

from prody2.objects import HAVE_CHEM, DcdMDSystem

class ProDyImportEnsemble(ProtImportFiles):
    """
    This protocol will import and optionally trim a ProDy Ensemble
    """
    _label = 'Import Ensemble'
    _possibleOutputs = {'outputAtomStructs': SetOfAtomStructs,
                        'outputNpz': ProDyNpzEnsemble}

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """

        form.addSection(label='Import ensemble')

        importChoices = self._getImportChoices()
        filesCondition = self._getFilesCondition()

        form.addParam('importFrom', params.EnumParam,
                      choices=importChoices, default=self._getDefaultChoice(),
                      label='Import from',
                      help='Select the type of import.')

        form.addParam('importType', params.EnumParam, choices=['pdb', 'dcd', 'ens.npz'],
                      default=PDB, condition=filesCondition,
                      label='Type of ensemble file to import',
                      help='ProDy can support import of ensembles in various file formats: \n'
                           'pdb, dcd and the native ens.npz format')

        form.addParam('importPointer', params.PointerParam,
                      pointerClass=POINTER_TYPES,
                      condition='importFrom!=0',
                      label='Ensemble file to import',
                      help='ProDy can support import of ensembles in various file formats: \n'
                           'pdb, dcd and the native ens.npz format')

        form.addParam('filesPath', params.PathParam,
                      label="Files directory", condition=filesCondition,
                      help="Directory with the files you want to import.\n\n"
                           "The path can also contain wildcards to select"
                           "from several folders. \n\n"
                           "Examples:\n"
                           "  ~/project/data/day??_files/\n"
                           "Each '?' represents one unknown character\n\n"
                           "  ~/project/data/day*_files/\n"
                           "'*' represents any number of unknown characters\n\n"
                           "  ~/project/data/day##_files/\n"
                           "'##' represents two digits that will be used as "
                           "file ID\n\n"
                           "NOTE: wildcard characters ('*', '?', '#') "
                           "cannot appear in the actual path.)")

        form.addParam('filesPattern', params.StringParam,
                      label='Pattern', condition=filesCondition,
                      help=filesPatternHelp)

        form.addParam('inputStructure', params.PointerParam, label="Input structure", allowsNull=True,
                      pointerClass='AtomStruct', condition="importType==%d or importFrom!=0" % DCD,
                      help='The input structure can be an atomic model '
                           '(true PDB) or a pseudoatomic model '
                           '(an EM volume converted into pseudoatoms). '
                           'The input structure should have the same number of atoms '
                           'as the original ensemble.')

        form.addParam('superpose', params.EnumParam, label="Superpose?",
                      choices=['No', 'Once', 'Iteratively'], default=NO_SUP,
                      help='Elect whether and how to superpose the ensemble')

        form.addParam('savePDBs', params.BooleanParam, default=False,
                      expertLevel=params.LEVEL_ADVANCED,
                      label="Save PDB files?",
                      help='This takes up storage and time, but '
                           'may be helpful for interfacing with ContinuousFlex.')

        form.addParam('selstr', params.StringParam, default="all",
                      label="Selection string",
                      help='Selection string for atoms to include in the ensemble.\n'
                           'It is recommended to use "all" (default), "protein" or "name CA"')

        form.addParam('writeDCDFile', params.BooleanParam, default=False,
                      expertLevel=params.LEVEL_ADVANCED,
                      condition="selstr!='all' or importType!=%d" % DCD,
                      label="Whether to write DCD trajectory file",
                      help='This will be registered as output too')

        form.addParam('inputPsf', params.PathParam, label="Input PSF topology", allowsNull=True,
                      condition="writeDCDFile==True or (selstr=='all' and importType==%d)"  % DCD,
                      help='An input psf topology can also be provided. '
                           'The psf should have the same number of atoms '
                           'as the original ensemble.')

    # --------------------------- STEPS functions ------------------------------
    def _insertAllSteps(self):
        # Insert processing steps
        self._insertFunctionStep('importEnsembleStep')
        self._insertFunctionStep('createOutputStep')

    def importEnsembleStep(self):      
        self.weights = None
        self.atoms = None

        if self.importFrom.get() == 0:
            filesPaths = self.getMatchFiles()
            folderPath = os.path.split(filesPaths[0])[0]
            self.pattern1 = os.path.split(filesPaths[0])[1]
            
            if self.importType == PDB:
                if not (self.pattern1.endswith('.pdb') or self.pattern1.endswith('.cif')):
                    self.pattern1 += '.pdb'
                self.atoms = prody.parsePDB(os.path.join(folderPath, self.pattern1))
                self.outEns = prody.PDBEnsemble(self.atoms)

            elif self.importType == DCD:
                if not self.pattern1.endswith('.dcd'):
                    self.pattern1 += '.dcd'
                self.outEns = prody.PDBEnsemble(prody.parseDCD(os.path.join(folderPath, self.pattern1)))

                if self.inputStructure.get() is not None:
                    self.atoms = prody.parsePDB(self.inputStructure.get().getFileName())

            elif self.importType == ENS_NPZ:
                if not self.pattern1.endswith('.ens.npz'):
                    self.pattern1 += '.ens.npz'
                self.outEns = prody.loadEnsemble(os.path.join(folderPath, self.pattern1))
                if not isinstance(self.outEns, prody.PDBEnsemble):
                    self.outEns = prody.PDBEnsemble(self.outEns)
                if 'size' in self.outEns.getDataLabels():
                    self.weights = self.outEns.getData('size')

                self.atoms = self.outEns.getAtoms()
        else:
            point = self.importPointer.get()

            if isinstance(point, ProDyNpzEnsemble):
                self.weights = [item.getAttributeValue(ENSEMBLE_WEIGHTS) for item in point]
                self.outEns = point.loadEnsemble()

                if self.inputStructure.get() is not None:
                    self.atoms = prody.parsePDB(self.inputStructure.get().getFileName())
                else:
                    self.atoms = self.outEns.getAtoms()

            elif isinstance(point, SetOfAtomStructs):
                self.weights = [item.getAttributeValue(ENSEMBLE_WEIGHTS) for item in point]
                self.ags = prody.parsePDB([struct.getFileName() for struct in point])
                self.outEns = prody.PDBEnsemble()
                self.outEns.setCoords(self.ags[0])
                for ag in self.ags:
                    self.outEns.addCoordset(ag)

                if self.inputStructure.get() is not None:
                    self.atoms = prody.parsePDB(self.inputStructure.get().getFileName())

            elif isinstance(point, AtomStruct):
                self.outEns = prody.PDBEnsemble(prody.parsePDB(point.getFileName()))
                if self.inputStructure.get() is not None:
                    self.atoms = prody.parsePDB(self.inputStructure.get().getFileName())

            else:
                # only activated if we can use MDSystem
                self.outEns = prody.PDBEnsemble(prody.parseDCD(point.getTrajectoryFile()))
                self.atoms = prody.parsePDB(point.getSystemFile())

        if self.weights is None or np.array_equal(np.array(self.weights), np.zeros(np.array(self.weights).shape)):
            self.weights = np.ones(self.outEns.numConfs())

        selstr = self.selstr.get()

        if self.atoms is not None:
            try:
                # setAtoms then select and trim
                self.outEns.setAtoms(self.atoms)
                self.outEns.setAtoms(self.atoms.select(selstr))
                self.outEns = prody.trimPDBEnsemble(self.outEns) # hard
            except ValueError:
                try:
                    # setAtoms with select directly then trim
                    self.outEns.setAtoms(self.atoms.select(selstr))
                    self.outEns = prody.trimPDBEnsemble(self.outEns) # hard
                except ValueError:
                    try:
                        # select then trim then setAtoms
                        self.outEns.select(selstr)
                        self.outEns = prody.trimPDBEnsemble(self.outEns) # hard
                        self.outEns.setAtoms(self.atoms.select(selstr))
                    except ValueError:
                        if hasattr(self, 'ags'):
                            try:
                                # setAtoms with first structure if available and trim
                                # then setAtoms with ref structure and trim again
                                self.outEns.setAtoms(self.ags[0])
                                self.outEns.setAtoms(self.ags[0].select(selstr))
                                self.outEns = prody.trimPDBEnsemble(self.outEns) # hard
                                self.outEns.setAtoms(self.atoms)
                                self.outEns.setAtoms(self.atoms.select(selstr))
                                self.outEns = prody.trimPDBEnsemble(self.outEns) # hard
                            except ValueError:
                                raise ValueError("Reference structure should have same number of atoms as ensemble")
                        else:
                            raise ValueError("Reference structure should have same number of atoms as ensemble")
        else:
            logger.warning("Reference structure not provided so selection will be ignored.")

        if self.superpose == YES_SUP:
            self.outEns.superpose()
        elif self.superpose == ITERPOSE:
            self.outEns.iterpose()
            
        if self.savePDBs.get():
            labels = self.outEns.getLabels()
            refLabel = labels[0]
            self.pdbs = SetOfAtomStructs().create(self._getExtraPath())
            for i, coordset in enumerate(self.outEns.getCoordsets()):
                atoms = self.atoms.select(selstr).copy()
                atoms.setCoords(coordset)
                filename = self._getExtraPath('{:s}_{:06d}_{:s}.pdb'.format(refLabel, i+1, labels[i]))
                prody.writePDB(filename, atoms)
                pdb = AtomStruct(filename)
                setattr(pdb, ENSEMBLE_WEIGHTS, pwobj.Float(self.weights[i]))
                self.pdbs.append(pdb)

        if self.inputPsf.get() is not None:
            psfAtoms = prody.parsePSF(self.inputPsf.get())
            if selstr=='all':
                os.symlink(self.inputPsf.get(), self._getPath(PSF_FILENAME))
            else:
                prody.writePSF(self._getPath(PSF_FILENAME), psfAtoms.select(selstr))

        prody.writePDB(self._getPath(PDB_FILENAME), self.outEns.getAtoms())
        if self.writeDCDFile.get():
            prody.writeDCD(self._getPath(DCD_FILENAME), self.outEns)
        elif self.selstr.get()=="all" and self.importType.get()==DCD:
            os.symlink(os.path.join(folderPath, self.pattern1), self._getPath(DCD_FILENAME))

        self.filename = prody.saveEnsemble(self.outEns, self._getExtraPath('ensemble.ens.npz'))

        self.npz = ProDyNpzEnsemble().create(self._getExtraPath())
        for i in range(self.outEns.numConfs()):
            frame = TrajFrame((i+1, self.filename), objLabel=self.outEns.getLabels()[i],
                              weight=pwobj.Float(self.weights[i]))
            self.npz.append(frame)

    def createOutputStep(self):
        outputs = {"outputNpz": self.npz}

        if self.writeDCDFile.get() or (self.selstr.get()=="all" and self.importType.get()==DCD):
            if HAVE_CHEM:
                outMDSystem = DcdMDSystem(filename=self._getPath(PDB_FILENAME))
                if os.path.exists(self._getPath(PSF_FILENAME)):
                    outMDSystem.setTopologyFile(self._getPath(PSF_FILENAME))
                else:
                    outMDSystem.setTopologyFile(self._getPath(PDB_FILENAME))
                outMDSystem.setTrajectoryFile(self._getPath(DCD_FILENAME))
                
                outputs["outputTrajectory"] = outMDSystem
            else:
                outEMFile = EMFile(filename=self._getPath(DCD_FILENAME))
                outputs["outputTrajectory"] = outEMFile

        if self.savePDBs.get():
            outputs["outputStructures"] = self.pdbs

        self._defineOutputs(**outputs)

    def _summary(self):
        if not hasattr(self, 'outputNpz'):
            summ = ['Output ensemble not ready yet']
        else:
            if len(self.outputNpz) < 100:
                ens = self.outputNpz.loadEnsemble()
                summ = ['Ensemble imported with *{0}* structures of *{1}* atoms'.format(
                    ens.numConfs(), ens.numAtoms())]
            else:
                summ = ['Ensemble imported with *{0}* structures'.format(len(self.outputNpz))]
        return summ

    def _getImportChoices(self):
        return ['files', 'pointer']

